apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: trivy-test
  namespace: pitc-cschlatter-midweek
spec:
  tasks:
    - name: git-clone
      params:
        - name: url
          value: 'https://github.com/schlapzz/insecure-node-app.git'
        - name: revision
          value: master
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-data
    - name: buildah-trivy-scan
      params:
        - name: IMAGE
          value: 'schlapzz/insecure:test'
        - name: BUILDER_IMAGE
          value: 'quay.io/buildah/stable:v1.15.1'
        - name: STORAGE_DRIVER
          value: overlay
        - name: DOCKERFILE
          value: ./Dockerfile
        - name: CONTEXT
          value: .
        - name: TLSVERIFY
          value: 'true'
        - name: FORMAT
          value: oci
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: buildah-trivy-scan
      workspaces:
        - name: source
          workspace: shared-data
  workspaces:
    - description: pass betwen tasks
      name: shared-data
