apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: full-trivy-scan
spec:
  params:
    - name: flags
      type: array
    - name: someURL
      type: string
  steps:
    - name: image-scan
      image: aquasec/trivy
      volumeMounts:
        - name: trivy-cache
          mountPath: /root/.cache/
      command:
        - trivy
      args:
      #  - --skip-update
        - --exit-code
        - "1"
        - --cache-dir
        - /root/.cache/trivy
        - $(input.resources.docker-build.name)
  inputs:
    resources:
      - name: docker-build
        type: image